#pragma once
#include <pgmspace.h>
inline const char PhotoPage[] PROGMEM = R"HTML(<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>我的图片吧唧</title>
<style>*{box-sizing:border-box}body{margin:0;background:#121625;color:#f5f1e8;font-family:system-ui,sans-serif;min-height:100vh}main{max-width:470px;margin:auto;padding:30px 24px}small{color:#a9ebd2;letter-spacing:3px}h1{font-size:32px;margin:12px 0}p{color:#aeb7c9;line-height:1.6}canvas{display:block;width:100%;aspect-ratio:1;border-radius:50%;background:#212a3c;touch-action:none;margin:24px 0;border:2px solid #5b716d}label,button{display:block;width:100%;padding:15px;border-radius:16px;border:0;font:inherit;text-align:center;cursor:pointer;background:#283346;color:#f7f3e9}button{background:#a9ebd2;color:#162f2b;margin-top:22px;font-weight:700}button:disabled{opacity:.4}input[type=file]{display:none}input[type=range]{width:100%;accent-color:#a9ebd2}#status{min-height:48px;text-align:center}footer{font-size:12px;color:#8390a5;text-align:center;margin-top:26px}</style>
<main><small>INFINITIME / BADGE STUDIO</small><h1>把喜欢的，戴在身上。</h1><p>选一张照片，拖动画面调整位置，再缩放到刚刚好。</p><label>选择图片<input id="file" type="file" accept="image/*"></label><canvas id="preview" width="466" height="466"></canvas><label for="zoom" style="background:none;padding:0;text-align:left">缩放</label><input id="zoom" type="range" min="1" max="3" step="0.01" value="1" disabled><button id="send" disabled>发送到吧唧</button><p id="status" role="status">图片只发到你的设备，不经过云端。</p><footer>上传后可关闭设备热点。照片断电后仍保留。</footer></main>
<script>
const file=document.querySelector('#file'),canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),zoom=document.querySelector('#zoom'),button=document.querySelector('#send'),status=document.querySelector('#status');let picture=null,px=0,py=0,drag=null;
function draw(){ctx.fillStyle='#212a3c';ctx.fillRect(0,0,466,466);if(!picture)return;const scale=Math.max(466/picture.width,466/picture.height)*Number(zoom.value),w=picture.width*scale,h=picture.height*scale;px=Math.max(-(w-466)/2,Math.min((w-466)/2,px));py=Math.max(-(h-466)/2,Math.min((h-466)/2,py));ctx.drawImage(picture,(466-w)/2+px,(466-h)/2+py,w,h)}
file.onchange=async()=>{const selected=file.files[0];if(!selected)return;button.disabled=true;status.textContent='正在读取图片…';try{const next=await createImageBitmap(selected,{imageOrientation:'from-image'});if(picture)picture.close();picture=next;px=py=0;zoom.value=1;zoom.disabled=false;draw();button.disabled=false;status.textContent='拖动圆形预览，调整构图。'}catch(e){status.textContent='无法读取，请选择 JPEG、PNG 或 WebP 图片。';button.disabled=!picture}};
zoom.oninput=draw;canvas.onpointerdown=e=>{if(!picture)return;drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;const factor=466/canvas.clientWidth;px+=(e.clientX-drag.x)*factor;py+=(e.clientY-drag.y)*factor;drag={x:e.clientX,y:e.clientY};draw()};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
function packFrame(rgba){const bytes=new Uint8Array(466*466*2);for(let i=0,j=0;i<rgba.length;i+=4,j+=2){const v=((rgba[i]>>3)<<11)|((rgba[i+1]>>2)<<5)|(rgba[i+2]>>3);bytes[j]=v&255;bytes[j+1]=v>>8}return bytes}
function crc32(bytes){let crc=0xffffffff;for(const value of bytes){crc^=value;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return ((crc^0xffffffff)>>>0).toString(16).padStart(8,'0')}
button.onclick=async()=>{button.disabled=true;status.textContent='正在发送，请保持连接…';try{const bytes=packFrame(ctx.getImageData(0,0,466,466).data),response=await fetch('/frame',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-CRC32':crc32(bytes)},body:bytes});if(!response.ok)throw new Error(await response.text());status.textContent='已保存到吧唧！现在可以关闭热点。'}catch(e){status.textContent='未完成：'+e.message+'。请保持热点连接后重试。'}finally{button.disabled=false}};draw();
</script></html>)HTML";
